spring:
  application:
    name: town-service
  datasource:
    url: ${DATA_BASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATA_BASE_USERNAME:postgres}
    password: ${DATA_BASE_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: off
    properties:
      hibernate:
        default_schema: application
  data:
    web:
      pageable:
        max-page-size: 20
  liquibase:
    change-log: classpath:db/changelog/master.yml
    liquibase-schema: migrations
    default-schema: migrations

springdoc:
  api-docs:
    enabled: true

server:
  port: ${SERVICE_PORT:8081}

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}